"""Initial models for 13 core entities

Revision ID: 08fbf0e3f1db
Revises: 
Create Date: 2026-08-29 18:09:39.807120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fbf0e3f1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_code', sa.String(length=16), nullable=False),
    sa.Column('host_session_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='LOBBY', nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('current_match_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['current_match_id'], ['matches.id'], name='fk_games_current_match', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_current_match_id'), ['current_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_game_code'), ['game_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_host_session_token'), ['host_session_token'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_categories_game_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_game_id'), ['game_id'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('timer_seconds', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'round_number', name='uq_rounds_game_round_number')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_game_id'), ['game_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(length=16), nullable=False),
    sa.Column('team_name', sa.String(length=50), nullable=False),
    sa.Column('leader_member_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['leader_member_id'], ['team_members.id'], name='fk_teams_leader_member', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_code', name='uq_teams_game_team_code')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_leader_member_id'), ['leader_member_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('match_order', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'match_order', name='uq_matches_round_match_order')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_opponent_team_id'), ['opponent_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_team_id'), ['team_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('device_role', sa.String(length=20), nullable=False),
    sa.Column('gameplay_role', sa.String(length=20), nullable=True),
    sa.Column('is_connected', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('connection_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_connection_token'), ['connection_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by_team_id', sa.Integer(), nullable=False),
    sa.Column('word_text', sa.String(length=100), nullable=False),
    sa.Column('normalized_word', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='AVAILABLE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_game_id'), ['game_id'], unique=False)
        batch_op.create_index('ix_words_game_status', ['game_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_normalized_word'), ['normalized_word'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_submitted_by_team_id'), ['submitted_by_team_id'], unique=False)

    op.create_table('device_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('connected_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sessions_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sessions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_sessions_session_token'), ['session_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_sessions_team_id'), ['team_id'], unique=False)

    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_team_id'), ['team_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('correct_words', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('passed_words', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_words', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('penalty_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('time_bonus_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_team_id'), ['team_id'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_word_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='WAITING', nullable=False),
    sa.Column('starting_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('remaining_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['current_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'turn_order', name='uq_turns_match_turn_order')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_current_word_id'), ['current_word_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turns_team_id'), ['team_id'], unique=False)

    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_turn_id'), ['turn_id'], unique=False)

    op.create_table('turn_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('result', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'sequence', name='uq_turn_words_sequence'),
    sa.UniqueConstraint('turn_id', 'word_id', name='uq_turn_words_word')
    )
    with op.batch_alter_table('turn_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turn_words_turn_id'), ['turn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turn_words_word_id'), ['word_id'], unique=False)

    op.create_foreign_key('fk_games_current_match', 'games', 'matches',
                          ['current_match_id'], ['id'])
    op.create_foreign_key('fk_teams_leader_member', 'teams', 'team_members',
                          ['leader_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # Tables are dropped in child-first dependency order. MySQL removes a
    # table's own indexes and foreign keys when the table is dropped, so only
    # the two deferred (use_alter) foreign keys need explicit removal first.
    op.drop_table('turn_words')
    op.drop_table('penalties')
    op.drop_table('turns')
    op.drop_table('scores')
    op.drop_table('game_events')
    op.drop_table('device_sessions')
    op.drop_table('words')
    op.drop_constraint('fk_teams_leader_member', 'teams', type_='foreignkey')
    op.drop_table('team_members')
    op.drop_constraint('fk_games_current_match', 'games', type_='foreignkey')
    op.drop_table('matches')
    op.drop_table('teams')
    op.drop_table('rounds')
    op.drop_table('categories')
    op.drop_table('games')
