"""add timer mode and pause/adjustment columns

Revision ID: ddfa399e4013
Revises: 72862d214dce
Create Date: 2026-08-29 20:41:59.483532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfa399e4013'
down_revision = '72862d214dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_mode', sa.String(length=20), server_default='COUNTDOWN', nullable=False))

    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pause_total_seconds', sa.Float(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('timer_adjustment_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_column('timer_adjustment_seconds')
        batch_op.drop_column('pause_total_seconds')
        batch_op.drop_column('paused_at')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('timer_mode')

    # ### end Alembic commands ###
